server:
  port: 6082
spring:
  application:
    name: weal-collect
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: weal-application
  #data:
   # mongodb:
    #  uri: mongodb://boms:boms@10.20.1.111:27017,10.20.1.111:27018,10.20.1.111:27019/boms-admin
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/weal?useUnicode=true&characterEncoding=utf8&useSSL=false
    #url: jdbc:log4jdbc:mysql://localhost:3306/boms_collect
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    #driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password: root
    druid:
      # 初始化大小
      initialSize: 5
      #最小连接池数量
      minIdle: 10
      #最大连接池数量
      maxActive: 300
      # 配置获取连接等待超时的时间 单位毫秒
      maxWait: 30000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      #单位秒，检测连接是否有效的超时时间
      validationQueryTimeout: 10
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: #stat,wall
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: guest
    password: guest
    #host: localhost
   # port: 5672
    #username: guest
    #password: guest
  redis:
    host: 127.0.0.1
    port: 6379
#    cluster:
#      nodes:
#      - 10.20.1.115:5371
#      - 10.20.1.115:5372
#      - 10.20.1.115:5373
#      - 10.20.1.115:5374
#      - 10.20.1.115:5375
#      - 10.20.1.115:5376
    jedis:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 20
        # 连接池中的最小空闲连接
        min-idle: 5
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 30000
    password: abc
    default_expirtime: 30
        
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.weal.storage.entity

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
###############################################job executor 配置#############################################
# log config
logging:
  config:
    classpath: logback-spring.xml

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9900/xxl-job-admin
### xxl-job executor address
    executor:
      appname: xxl-job-executor-sample-weal
      ip: 127.0.0.1
      #ip: 10.20.0.28
      port: 39999
### xxl-job log path
      logpath: /data/service/boms-collect/xxl-logs
### xxl-job log retention days
      logretentiondays: 3
### xxl-job, access token
    accessToken:
################################################## end #####################################################

############################# 数据采集监听器配置 start ######################
collect:
  wan500:
    wealUrl: http://live.500.com/wanchang.php
instance:
  health:
    concurrency: 20 #实例健康检测并发数，根据实例多少而定
clean:
  concurrency: 10 #清洗注册中心数据的并发数
install:
  concurrency: 20 #组装注册中心数据的并发数

############################## 数据采集监听器配置 end #######################